require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'memo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'memoTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  
  # use_flipper!({ 'Flipper' => '0.74.0' })
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end

  pod 'Google-Mobile-Ads-SDK', '7.69.0'

end

target 'memo-tvOS' do
  # Pods for memo-tvOS

  target 'memo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
